export const bodyData = [
	{
		firstName: "chloe",
		lastName: "ruard",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
	{
		firstName: "chloe2",
		lastName: "ruard2",
		birthDate: "12/12/12",
		startDate: "01/02/03",
		street: "street",
		city: "city",
		state: "Florida",
		stateShort: "FL",
		zipCode: "3873985",
		department: "Human Resources",
	},
];